### ISSUE TITLE
Got an error when I tried to publish an EML object

### ISSUE THREAD

**Issue by taojing2002** [NCEAS/osti-elink#4]
I got this error when I published a package:
```
metacat 20241024-14:53:40: [INFO]: MNodeService.query - the solr query is === fl=id,resourceMap&wt=xml&q=id:"urn:uuid:81ce278f-b6c8-4dd0-85dc-e7e6c289b5d2" [edu.ucsb.nceas.metacat.dataone.MNodeService:query:2207]
metacat 20241024-14:53:40: [WARN]: DOIService.getLandingPage - the landing page url is: https://valley.duckdns.org/metacatui/view/doi:10.15485/2304961 [edu.ucsb.nceas.metacat.doi.DOIService:getLandingPage:127]
metacat 20241024-14:53:40: [INFO]: The url sending to the service is https://review.osti.gov/elink2api/records?doi=%2210.15485%2F2304961%22 [edu.ucsb.nceas.osti_elink.v2.xml.OSTIv2XmlService:getMetadata:176]
metacat 20241024-14:53:40: [INFO]: The response for id 10.15485/2304961 is
 [{"description":"This data package includes a time-series of field measurements from March to October 2021 in 
groundwater and surface water from the Slate River floodplain in Crested Butte, CO, a focus field site for the SLAC 
Floodplain Hydro-Biogeochemistry SFA. The data was generated as part of the work targeting the overarching research 
question for the SLAC SFA: How do ubiquitous subsurface interfaces mediate molecular-scale biogeochemical processes
and groundwater quality in floodplains and watersheds? The data package includes 5 data files, one for each measured
variable: specific conductivity, pH, dissolved oxygen, water temperature and alkalinity. All measurements were recorded in
the field immediately after water sampling. Groundwater samples were extracted from a network of installed rhizons
(Rhizosphere Research Products, part no. 19.60.21F, 0.6 micrometer mesh size) and piezometer wells within the
floodplain. In addition to the data files, there is a terminology file explaining the terms used, a file level metadata file, and a
sensor file with metadata about the sensors used.All files are in csv format.","doi":"10.15485/2304961","geolocations
[{"type":"BOX","label":"The Slate River (SR) a snow-dominated, headwater basin of the Upper Colorado River Basin
(UCRB) located in the western United States. The SR is located just north of the town of Crested Butte, CO.","points
[{"latitude":38.910142,"longitude":-107.030593},{"latitude":38.896436,"longitude":-107.011096}]}],"languages
["English"],"title":"Specific conductivity, pH, dissolved oxygen, water temperature and alkalinity in-situ data; Slate River
floodplain, Crested Butte, CO; March 2021-October 2021","persons":[{"type":"AUTHOR","email
["swpierce@slac.stanford.edu"],"affiliations":[{"name":"SLAC National Accelerator
Laboratory"}],"first_name":"Samuel","last_name":"Pierce","orcid":"0000000176140227"},{"type":"AUTHOR","email"
["bargar@slac.stanford.edu"],"affiliations":[{"name":"SLAC National Accelerator
Laboratory"}],"first_name":"John","last_name":"Bargar","orcid":"0000000193034901"},{"type":"CONTACT","email
["swpierce@slac.stanford.edu"],"affiliations":[],"first_name":"Samuel","last_name":"Pierce"}],"organizations
[{"identifiers":[],"type":"SPONSOR","name":"U.S. DOE > Office of Science > Biological and Environmental Research
(BER)"},{"identifiers":[],"type":"RESEARCHING","name":"Groundwater Quality SFA"}],"identifiers"
[{"type":"CN_DOE","value":"AC02-05CH11231"}],"media":[],"osti_id":2304961,"revision":2,"access_limitations
["UNL"],"ANALYTIC_FLAG":false,"collection_type":"DOE_LAB","country_publication_code":"US","added_by":118777,
"edied_by":118777,"date_added":"2024-10-24T21:27:14.086+00:00","doe_supported_flag":false,"keywords":["EARTH
SCIENCE > TERRESTRIAL HYDROSPHERE > WATER QUALITY/WATER CHEMISTRY > GASES > DISSOLVED
OXYGEN","EARTH SCIENCE > TERRESTRIAL HYDROSPHERE > WATER QUALITY/WATER CHEMISTRY > WATER
CHARACTERISTICS > ALKALINITY","EARTH SCIENCE > TERRESTRIAL HYDROSPHERE > WATER QUALITY/WATER
CHEMISTRY > WATER CHARACTERISTICS > CONDUCTIVITY","EARTH SCIENCE > TERRESTRIAL HYDROSPHERE >
WATER QUALITY/WATER CHEMISTRY > WATER CHARACTERISTICS > WATER TEMPERATURE","EARTH SCIENCE >
TERRESTRIAL HYDROSPHERE > WATER QUALITY/WATER CHEMISTRY > WATER CHARACTERISTICS > pH","EARTH
SCIENCE > TERRESTRIAL HYDROSPHERE > GROUND WATER > GROUNDWATER CHEMISTRY","EARTH SCIENCE > LAND
SURFACE > SOILS","EARTH SCIENCE > TERRESTRIAL HYDROSPHERE > GROUND WATER","EARTH SCIENCE >
TERRESTRIAL HYDROSPHERE > WATER QUALITY/WATER CHEMISTRY","EARTH SCIENCE > TERRESTRIAL
HYDROSPHERE > WATER QUALITY/WATER CHEMISTRY > GASES > DISSOLVED OXYGEN","EARTH SCIENCE >
TERRESTRIAL HYDROSPHERE > WATER QUALITY/WATER CHEMISTRY > WATER CHARACTERISTICS >
ALKALINITY","EARTH SCIENCE > TERRESTRIAL HYDROSPHERE > WATER QUALITY/WATER CHEMISTRY > WATER
CHARACTERISTICS > CONDUCTIVITY","EARTH SCIENCE > TERRESTRIAL HYDROSPHERE > WATER QUALITY/WATER
CHEMISTRY > WATER CHARACTERISTICS > WATER TEMPERATURE","EARTH SCIENCE > TERRESTRIAL HYDROSPHERE >
WATER QUALITY/WATER CHEMISTRY > WATER CHARACTERISTICS >pH"],"paper_flag":false,"product_type":"DA","publication_date":"2021-10-26","site_ownership_code":
"ESSDIVE","source_edit_type":"DOE_LAB_API","source_input_type":"DOE_LAB_API","subject_category_code
["54"],"subject_category_code_legacy":[],"peer_reviewed_flag":false,"related_identifiers
[],"workflow_status":"SA","edit_reason":"API metadata update.","edit_source":"NORMAL_API","date_updated":"2024-10
24T21:34:45.478+00:00"}] [edu.ucsb.nceas.osti_elink.v2.xml.OSTIv2XmlService:getMetadata:179]
Exception in thread "pool-17-thread-4" java.lang.NoSuchMethodError:
'com.fasterxml.jackson.core.JsonParser$NumberTypeFP com.fasterxml.jackson.core.JsonParser.getNumberTypeFP()'
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._fromFloat(JsonNodeDeserializer.java:765)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeContainerNoRecursion(JsonNodeDeserializer.java:578)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:104)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4959)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3281)
	at edu.ucsb.nceas.osti_elink.v2.response.JsonResponseHandler.getPathValue(JsonResponseHandler.java:23)
	at edu.ucsb.nceas.osti_elink.v2.xml.OSTIv2XmlService.parseOSTIidFromResponse(OSTIv2XmlService.java:210)
	at edu.ucsb.nceas.osti_elink.OSTIElinkService.getOstiId(OSTIElinkService.java:518)
	at edu.ucsb.nceas.osti_elink.OSTIElinkService.setMetadata(OSTIElinkService.java:214)
	at edu.ucsb.nceas.osti_elink.OSTIElinkServiceRequest.run(OSTIElinkServiceRequest.java:89)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by taojing2002** [comment]
The issue is the compatibility of the jackson json library in Metacat. So the fix is in the Metacat repository. When I made them the same version, the issue is gone.
